### PR TITLE
fixed UI on 2019 challenges

### PR DESCRIPTION
**Pull request by websupergirl**
Made videos responsive on the 2019 challenges page and added bootstrap structure to create uniformity in order to fix other things later on.

### CODE REVIEW

**Comment by csjoblom** [comment]
Unsure you want to add bootstrap and jquery considering you have vue access, but I'll leave that up to @antonioortegajr

**Comment by websupergirl** [comment]
@csjoblom The tech choice was made as an interim measure to fix something immediate - I'm working on a more long term plan to update all the things that would allow me to integrate this in a more proper way. Right now the versions of nuxt is way behind current and updating a few things causes catastrophic failure. For example, you can use Bootstrap Vue (without jquery) but it requires a min of nuxt 2.10 ... and this thing is on nuxt 1.0.

**Review by antonioortegajr — COMMENTED** [review]
I think bringing in bootstrap and jQuery is a bit much. For mobile responsiveness of the videos wouldn't changing 
.h4c-challenges {
    width: 560px;
}
To width: 100% work and avoid the boot and jQ overhead?

**Comment by csjoblom** [comment]
Pretty heavy handed for what you are trying to accomplish I would recommend using scoped css that Antonio has provided. No need for bootstrap at all.

**Comment by websupergirl** [comment]
I am attempting to standardize the site with a well documented code base
that actually works, unlike the css code provided which does not account
for aspect ratio of videos nor graceful degradation of the layout on
different devices.

**Comment by csjoblom** [comment]
@websupergirl this project already includes bootstrap 4, its included in package.json. Since you have access to vue there is no need for jquery. This project is also es6 compatible.

**Pull request closed without merging**
